# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zap < Formula
  desc ""
  homepage "https://github.com/sudonym-btc/zap"
  version "0.0.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sudonym-btc/zap/releases/download/v0.0.1/zap_Darwin_arm64.tar.gz"
      sha256 "4d3214809504e947d23094d67f6bf46076f9541b74bbc52cdfb5a8eb515ccb9a"

      def install
        bin.install "zap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sudonym-btc/zap/releases/download/v0.0.1/zap_Darwin_x86_64.tar.gz"
      sha256 "9a39e95dd9415e5b81368d3e0cadba664624c69343ce57023d66afe30b155f66"

      def install
        bin.install "zap"
      end
    end
  end
end
